python3 -m unitttest -v funcional.py
✅ Todos os testes passaram com sucesso!
Veja a saída de erro para conferir
